#!/bin/bash
wget https://se.math.spbu.ru/thesis/texts/Maksimenko_Dmitrij_Sergeevich_Bachelor_Thesis_2021_text.pdf
mv Maksimenko_Dmitrij_Sergeevich_Bachelor_Thesis_2021_text.pdf pdf_example_cw1.pdf
wget https://se.math.spbu.ru/thesis/texts/Svirin_Evgenij_Aleksandrovich_Bachelor_Thesis_2021_text.pdf
mv Svirin_Evgenij_Aleksandrovich_Bachelor_Thesis_2021_text.pdf pdf_example_cw2.pdf
wget https://se.math.spbu.ru/thesis/texts/Tuchina_Anastasija_Igorevna_Bachelor_Report_2019_text.pdf
mv Tuchina_Anastasija_Igorevna_Bachelor_Report_2019_text.pdf pdf_example_cw3.pdf
